### ISSUE TITLE
CasADi 3.6.0 compatibility

### ISSUE THREAD

**Issue by FreyJo** [FreyJo/nosnoc_py#45]
While this CasADi 3.6.0 has quite some new nice features, it also introduces incompatibilities.
Ideally, we make it compatible with both 3.5 and 3.6.
https://github.com/FreyJo/nosnoc_py/actions/runs/4676105466/jobs/8281997671?pr=44

Breaking changes are listed here
https://github.com/casadi/casadi/releases/tag/3.6.0

**Comment by apozharski** [comment]
handled in #47
